services:
  backend:
    secrets:
      - db-password
    depends_on:
      - database
    environment:
      - DEBUG=False
  database:
    build: database/
    secrets:
      - db-password
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password

secrets:
  db-password:
    file: database/password.txt
