services:
  backend:
    ports:
      - 8080:8080
    environment:
      - DEBUG=True
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - __pycache__/
