# Generated by Django 5.0.6 on 2024-05-23 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.TextField()),
                ('comment', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_blocks', to='Courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='TheoryBlock',
            fields=[
                ('id_page', models.UUIDField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='theory_images/')),
                ('captioned_image', models.ImageField(blank=True, upload_to='captioned_images/')),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('page_number', models.IntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theory_blocks', to='Courses.course')),
            ],
        ),
    ]
